name: Secret Printer

on:
  push:
    branches: [ "main" ]

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
    - name: python print secret
      env:
        SECRET_LOGIN: ${{ secrets.SECRET_LOGIN }}
        SECRET_DB: ${{ secrets.SECRET_DB }}
      run: |
        import os
        for q in (os.getenv("SECRET_LOGIN")):
          print(q)
        
        for q in (os.getenv("SECRET_DB")):
          print(q)
      shell: python