name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: dryabokon/tools
        path: tools/

    - name: Run tests
      env:
        SECRET_LOGIN: ${{ secrets.SECRET_DB }}

      run: |
        python main.py "$env:SECRET_LOGIN"