name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

#    - name: Install dependencies
#      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#    - name: Clone repository
#      uses: actions/checkout@v3
#      with:
#        repository: dryabokon/tools
#        path: tools/

    - name: Run tests
      env:
        SECRET_LOGIN: ${{ secrets.SECRET_LOGIN }}

      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
          data.write(q)
      shell: python